baseURL = 'http://example.org/'
languageCode = 'es'
title = 'Prueba Hugo Site'
theme = "tale"

[menu]
[[menu.main]]
  identifier = 'contacto'
  name = 'Contacto'
  title= 'Contacto'
  pre = "<i class='fa fa-heart'></i>"
  url = '/contacto/'
  weight = -110
[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  title= 'Posts'
  pre = "<i class='fa fa-heart'></i>"
  url = '/posts/'
  weight = -100